services:
  - type: web
    name: pod
    runtime: static
    repo: https://github.com/Pannatornn/pod
    branch: main
    buildCommand: npm run build
    staticPublishPath: ./out
    autoDeployTrigger: commit
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
