services:
  - type: web
    name: pod
    runtime: static
    repo: https://github.com/Pannatornn/pod
    branch: main
    buildCommand: POD_STATIC_EXPORT=1 npm run build
    staticPublishPath: ./out
    autoDeployTrigger: commit
